In [133]:
import seaborn as sns
import pandas as pd
import math
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [64]:
my_access_token = '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'

!git config --global user.email "rlchhua@ucdavis.edu"
!git config --global user.name "Raymond"

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [122]:
data = pd.read_csv('/content/drive/MyDrive/ECS_171_Files/ECS171/popular_10000_movies_tmdb.csv')

In [123]:
data = data.drop(columns=["title"])
data = data.drop(columns=['tagline'])
data = data.drop(columns=['overview'])
data = data.drop(columns=['original_language'])

In [124]:
data = data.replace({'release_date':'-'}, {'release_date':''}, regex=True)

In [125]:
data = data.dropna()

In [126]:
budget_mean = math.floor(data['budget'].mean())
data = data.replace({'budget':0}, {'budget':budget_mean}, regex=True)

revenue_mean = math.floor(data['revenue'].mean())
data = data.replace({'revenue':0}, {'revenue':revenue_mean}, regex=True)

In [127]:
lengths = []
for row in data['genres']:
    lengths.append(row.count(',') + 1)

data['genres'] = lengths

lengths = []
for row in data['production_companies']:
    lengths.append(row.count(',') + 1)

data['production_companies'] = lengths

In [130]:
data

,id,release_date,genres,vote_average,vote_count,popularity,budget,production_companies,revenue,runtime
0,758323,20230405,3,7.4,619,5089.969,18000000,6,65675816,103
1,640146,20230215,3,6.6,2294,4665.438,200000000,2,464566092,125
2,502356,20230405,5,7.5,1861,3935.550,100000000,3,1121048165,92
3,868759,20230418,3,7.2,652,2791.532,19545617,2,59895039,120
4,594767,20230315,4,6.8,1510,2702.593,125000000,4,133437105,130
...,...,...,...,...,...,...,...,...,...,...
9995,374473,20161021,1,7.7,1220,10.774,19545617,6,15793051,100
9996,16774,20061028,7,6.3,99,12.739,19545617,2,59895039,73
9997,13564,20071003,2,5.6,263,12.769,19545617,2,59895039,81
9998,482204,20170831,2,5.0,5,10.425,19545617,1,59895039,89
9999,444539,20171110,1,6.5,382,12.525,5400000,3,12055868,110

In [144]:
X_train, X_test, y_train, y_test = train_test_split(data['budget'], data['revenue'], test_size=0.1, random_state=42)

In [148]:
reg = LinearRegression()
regmodel = reg.fit(X_train.values.reshape(-1,1), y_train.values.reshape(-1,1))

In [150]:
yhat_train = reg.predict(X_train.values.reshape(-1,1))
yhat_test = reg.predict(X_test.values.reshape(-1,1))

In [151]:
print('\nMean squared error Train: %.2f' % mean_squared_error(y_train, yhat_train))
print('\nMean squared error Test: %.2f' % mean_squared_error(y_test, yhat_test))

Mean squared error Train: 11085842654402354.00

Mean squared error Test: 9427517431498930.00